# core/ygoenv/constants.py

# --- Types ---
TYPE_MONSTER = 0x1
TYPE_SPELL = 0x2
TYPE_TRAP = 0x4
TYPE_NORMAL = 0x10
TYPE_EFFECT = 0x20
TYPE_FUSION = 0x40
TYPE_RITUAL = 0x80
TYPE_TRAPMONSTER = 0x100
TYPE_SPIRIT = 0x200
TYPE_UNION = 0x400
TYPE_GEMINI = 0x800
TYPE_TUNER = 0x1000
TYPE_SYNCHRO = 0x2000
TYPE_TOKEN = 0x4000
TYPE_MAXIMUM = 0x8000
TYPE_QUICKPLAY = 0x10000
TYPE_CONTINUOUS = 0x20000
TYPE_EQUIP = 0x40000
TYPE_FIELD = 0x80000
TYPE_COUNTER = 0x100000
TYPE_FLIP = 0x200000
TYPE_TOON = 0x400000
TYPE_XYZ = 0x800000
TYPE_PENDULUM = 0x1000000
TYPE_SPSUMMON = 0x2000000
TYPE_LINK = 0x4000000

# Mapping from YGOPRODeck String "type" to C++ Type Bitmask
YGO_TYPE_MAPPING = {
    "Normal Monster": TYPE_MONSTER | TYPE_NORMAL,
    "Normal Tuner Monster": TYPE_MONSTER | TYPE_NORMAL | TYPE_TUNER,
    "Effect Monster": TYPE_MONSTER | TYPE_EFFECT,
    "Tuner Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_TUNER,
    "Flip Effect Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_FLIP,
    "Flip Tuner Effect Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_FLIP | TYPE_TUNER,
    "Spirit Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_SPIRIT,
    "Toon Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_TOON,
    "Gemini Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_GEMINI,
    "Union Effect Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_UNION,
    "Union Tuner Effect Monster": TYPE_MONSTER | TYPE_EFFECT | TYPE_UNION | TYPE_TUNER,
    
    "Ritual Monster": TYPE_MONSTER | TYPE_RITUAL,
    "Ritual Effect Monster": TYPE_MONSTER | TYPE_RITUAL | TYPE_EFFECT,
    
    "Fusion Monster": TYPE_MONSTER | TYPE_FUSION,
    "Fusion Tuner Monster": TYPE_MONSTER | TYPE_FUSION | TYPE_TUNER,
    
    "Synchro Monster": TYPE_MONSTER | TYPE_SYNCHRO,
    "Synchro Tuner Monster": TYPE_MONSTER | TYPE_SYNCHRO | TYPE_TUNER,
    "Synchro Pendulum Effect Monster": TYPE_MONSTER | TYPE_SYNCHRO | TYPE_PENDULUM | TYPE_EFFECT,
    
    "XYZ Monster": TYPE_MONSTER | TYPE_XYZ,
    "XYZ Pendulum Effect Monster": TYPE_MONSTER | TYPE_XYZ | TYPE_PENDULUM | TYPE_EFFECT,
    
    "Link Monster": TYPE_MONSTER | TYPE_LINK,
    
    "Pendulum Normal Monster": TYPE_MONSTER | TYPE_PENDULUM | TYPE_NORMAL,
    "Pendulum Effect Monster": TYPE_MONSTER | TYPE_PENDULUM | TYPE_EFFECT,
    "Pendulum Tuner Effect Monster": TYPE_MONSTER | TYPE_PENDULUM | TYPE_EFFECT | TYPE_TUNER,
    "Pendulum Flip Effect Monster": TYPE_MONSTER | TYPE_PENDULUM | TYPE_EFFECT | TYPE_FLIP,
    "Pendulum Effect Fusion Monster": TYPE_MONSTER | TYPE_PENDULUM | TYPE_EFFECT | TYPE_FUSION,
    
    "Spell Card": TYPE_SPELL,
    "Trap Card": TYPE_TRAP,
    
    "Token": TYPE_MONSTER | TYPE_TOKEN
}

# --- Attributes ---
ATTRIBUTE_EARTH = 0x01
ATTRIBUTE_WATER = 0x02
ATTRIBUTE_FIRE = 0x04
ATTRIBUTE_WIND = 0x08
ATTRIBUTE_LIGHT = 0x10
ATTRIBUTE_DARK = 0x20
ATTRIBUTE_DIVINE = 0x40

YGO_ATTRIBUTE_MAPPING = {
    "EARTH": ATTRIBUTE_EARTH,
    "WATER": ATTRIBUTE_WATER,
    "FIRE": ATTRIBUTE_FIRE,
    "WIND": ATTRIBUTE_WIND,
    "LIGHT": ATTRIBUTE_LIGHT,
    "DARK": ATTRIBUTE_DARK,
    "DIVINE": ATTRIBUTE_DIVINE
}

# --- Races (Monster Types) ---
RACE_WARRIOR = 0x1
RACE_SPELLCASTER = 0x2
RACE_FAIRY = 0x4
RACE_FIEND = 0x8
RACE_ZOMBIE = 0x10
RACE_MACHINE = 0x20
RACE_AQUA = 0x40
RACE_PYRO = 0x80
RACE_ROCK = 0x100
RACE_WINGEDBEAST = 0x200
RACE_PLANT = 0x400
RACE_INSECT = 0x800
RACE_THUNDER = 0x1000
RACE_DRAGON = 0x2000
RACE_BEAST = 0x4000
RACE_BEASTWARRIOR = 0x8000
RACE_DINOSAUR = 0x10000
RACE_FISH = 0x20000
RACE_SEASERPENT = 0x40000
RACE_REPTILE = 0x80000
RACE_PSYCHIC = 0x100000
RACE_DIVINE = 0x200000
RACE_CREATORGOD = 0x400000
RACE_WYRM = 0x800000
RACE_CYBERSE = 0x1000000
RACE_ILLUSION = 0x2000000

YGO_RACE_MAPPING = {
    "Warrior": RACE_WARRIOR,
    "Spellcaster": RACE_SPELLCASTER,
    "Fairy": RACE_FAIRY,
    "Fiend": RACE_FIEND,
    "Zombie": RACE_ZOMBIE,
    "Machine": RACE_MACHINE,
    "Aqua": RACE_AQUA,
    "Pyro": RACE_PYRO,
    "Rock": RACE_ROCK,
    "Winged Beast": RACE_WINGEDBEAST,
    "Plant": RACE_PLANT,
    "Insect": RACE_INSECT,
    "Thunder": RACE_THUNDER,
    "Dragon": RACE_DRAGON,
    "Beast": RACE_BEAST,
    "Beast-Warrior": RACE_BEASTWARRIOR,
    "Dinosaur": RACE_DINOSAUR,
    "Fish": RACE_FISH,
    "Sea Serpent": RACE_SEASERPENT,
    "Reptile": RACE_REPTILE,
    "Psychic": RACE_PSYCHIC,
    "Divine-Beast": RACE_DIVINE,
    "Creator-God": RACE_CREATORGOD,
    "Wyrm": RACE_WYRM,
    "Cyberse": RACE_CYBERSE,
    "Illusion": RACE_ILLUSION,
    "Illusionist": RACE_ILLUSION, # Sometime listed as Illusionist
    
    # For Spells and Traps
    "Normal": TYPE_NORMAL,
    "Continuous": TYPE_CONTINUOUS,
    "Equip": TYPE_EQUIP,
    "Field": TYPE_FIELD,
    "Quick-Play": TYPE_QUICKPLAY,
    "Ritual": TYPE_RITUAL,
    "Counter": TYPE_COUNTER
}

# --- Network Messages ---
MSG_RETRY = 1
MSG_HINT = 2
MSG_WAITING = 3
MSG_START = 4
MSG_WIN = 5
MSG_UPDATE_DATA = 6
MSG_UPDATE_CARD = 7
MSG_REQUEST_DECK = 8
MSG_SELECT_BATTLECMD = 10
MSG_SELECT_IDLECMD = 11
MSG_SELECT_EFFECTYN = 12
MSG_SELECT_YESNO = 13
MSG_SELECT_OPTION = 14
MSG_SELECT_CARD = 15
MSG_SELECT_CHAIN = 16
MSG_SELECT_PLACE = 18
MSG_SELECT_POSITION = 19
MSG_SELECT_TRIBUTE = 20
MSG_SELECT_COUNTER = 22
MSG_SELECT_SUM = 23
MSG_SELECT_DISFIELD = 24
MSG_SELECT_UNSELECT_CARD = 26

# --- Query Flags ---
QUERY_CODE = 0x1
QUERY_POSITION = 0x2
QUERY_ALIAS = 0x4
QUERY_TYPE = 0x8
QUERY_LEVEL = 0x10
QUERY_RANK = 0x20
QUERY_ATTRIBUTE = 0x40
QUERY_RACE = 0x80
QUERY_ATTACK = 0x100
QUERY_DEFENSE = 0x200
QUERY_BASE_ATTACK = 0x400
QUERY_BASE_DEFENSE = 0x800
QUERY_REASON = 0x1000
QUERY_EQUIP_CARD = 0x4000
QUERY_TARGET_CARD = 0x8000
QUERY_OVERLAY_CARD = 0x10000
QUERY_COUNTERS = 0x20000
QUERY_OWNER = 0x40000
QUERY_STATUS = 0x80000
QUERY_LSCALE = 0x200000
QUERY_RSCALE = 0x400000
QUERY_LINK = 0x800000
QUERY_END = 0x80000000
