"""Apply review patches: CASCADE, indexes, String lengths and timezone

Revision ID: 3a99862fb5bf
Revises: c28db669e176
Create Date: 2026-06-12 10:30:23.774235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a99862fb5bf'
down_revision: Union[str, Sequence[str], None] = 'c28db669e176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_game_transitions_duel_id'), 'game_transitions', ['duel_id'], unique=False)
    # op.drop_constraint(None, 'game_transitions', type_='foreignkey')
    # op.create_foreign_key(None, 'game_transitions', 'duel_stats', ['duel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_transitions', type_='foreignkey')
    op.create_foreign_key(None, 'game_transitions', 'duel_stats', ['duel_id'], ['id'])
    op.drop_index(op.f('ix_game_transitions_duel_id'), table_name='game_transitions')
    # ### end Alembic commands ###
