"""Add Card schema

Revision ID: 955eb4f3f86b
Revises: 3a99862fb5bf
Create Date: 2026-06-12 23:52:48.790760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955eb4f3f86b'
down_revision: Union[str, Sequence[str], None] = '3a99862fb5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('race', sa.String(length=100), nullable=True),
    sa.Column('archetype', sa.String(length=100), nullable=True),
    sa.Column('atk', sa.Integer(), nullable=True),
    sa.Column('def_', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('attribute', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_name'), 'cards', ['name'], unique=False)
    # op.drop_constraint(None, 'game_transitions', type_='foreignkey')
    # op.create_foreign_key(None, 'game_transitions', 'duel_stats', ['duel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game_transitions', type_='foreignkey')
    op.create_foreign_key(None, 'game_transitions', 'duel_stats', ['duel_id'], ['id'])
    op.drop_index(op.f('ix_cards_name'), table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###
