"""Initial schema

Revision ID: c28db669e176
Revises: 
Create Date: 2026-06-12 10:15:34.541722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c28db669e176'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duel_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_1_deck', sa.String(length=255), nullable=False),
    sa.Column('player_2_deck', sa.String(length=255), nullable=False),
    sa.Column('winner', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('duel_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('reward', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['duel_id'], ['duel_stats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_transitions')
    op.drop_table('duel_stats')
    # ### end Alembic commands ###
